name: Deploy to Oracle Cloud

on:
  push:
    branches:
      - main  # change to your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/mini-drive
            git pull origin main
            cd apps/api-server
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart fastapi
